# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 50
  log_file: /h/addisonw/fairseq/logs/gaussianNoise/log.json

checkpoint:
  save_dir: /h/addisonw/fairseq/checkpoints/gaussianNoise
  save_interval: 5
  save_interval_updates: 10000
  keep_interval_updates: 1 # ie only keep most recent checkpoint
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: audio_finetuning
  data: ???
  normalize: true
  labels: ltr
  eval_wer: true

dataset:
  num_workers: 2
  max_tokens: 1280000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 0
  validate_interval: 1
  valid_subset: valid

distributed_training:
  ddp_backend: legacy_ddp
  #distributed_world_size: 4

criterion:
  _name: ctc
  zero_infinity: true
  wer_kenlm_model: /h/addisonw/fairseq/pretrained_models/kenlm/4-gram.bin # LM for decoding
  wer_lexicon: /h/addisonw/fairseq/pretrained_models/kenlm/lexicon.txt
  wer_lm_weight: 2
  wer_word_score: -1

optimization:
  max_update: 20000
  lr: [0.0001]
  sentence_avg: true
  update_freq: [5]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.75
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000

#add_gaussian_train_noise: true
#add_uniform_train_noise: false